### ISSUE TITLE
Support user defined resource quota.

### ISSUE THREAD

**Issue by BalaBalaYi** [intelligent-machine-learning/dlrover#1432]
**Is your feature request related to a problem? Please describe.**
Need to specified master's resource quota.

**Describe the solution you'd like**
We can enable setting the master pod spec in the elasticjob like a worker pod spec. Then, the user can configure the command and resource of the master pod.

**Describe alternatives you've considered**

**Additional context**

**Comment by workingloong** [comment]
Now, user can specify the master source like worker because the replicaSpecs is a map.https://github.com/intelligent-machine-learning/dlrover/blob/70bc9086106ae67cb213708d69122b15d680daf4/go/elasticjob/api/v1alpha1/elasticjob_types.go#L56

https://github.com/intelligent-machine-learning/dlrover/blob/70bc9086106ae67cb213708d69122b15d680daf4/go/elasticjob/pkg/controllers/master/master.go#L64-L66

For example:

```
---
apiVersion: elastic.iml.github.io/v1alpha1
kind: ElasticJob
metadata:
  name: fine-tuning-llama2
  namespace: dlrover
spec:
  distributionStrategy: AllreduceStrategy
  optimizeMode: single-job
  replicaSpecs:
    worker:
      replicas: 2
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              # yamllint disable-line rule:line-length
              image: registry.cn-hangzhou.aliyuncs.com/intell-ai/dlrover:llama-finetuning
              imagePullPolicy: Always
              command:
                - /bin/bash
                - -c
                - "dlrover-run --nnodes=$NODE_NUM \
                  --nproc_per_node=1 --max_restarts=1  \
                  ./examples/pytorch/llama2/fine_tuning.py  \
                  ./examples/pytorch/llama2/btc_tweets_sentiment.json"
              resources:
                limits:
                  cpu: "8"
                  memory: 16Gi
                  nvidia.com/gpu: 1  # optional
                requests:
                  cpu: "4"
                  memory: 16Gi
                  nvidia.com/gpu: 1  # optional
    dlrover-master:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              # yamllint disable-line rule:line-length
              image: easydl/elasticjob-controller:master
              imagePullPolicy: Always
              command:
                - /bin/bash
                - -c
                - "python -m  dlrover.python.master.main --xxx"
              resources:
                limits:
                  cpu: "1"
                  memory: 2Gi
                  nvidia.com/gpu: 1  # optional
                requests:
                  cpu: "1"
                  memory: 2Gi
                  nvidia.com/gpu: 1  # optional
```
