### ISSUE TITLE
Cannot initialize brain channel

### ISSUE THREAD

**Issue by youxingling** [intelligent-machine-learning/dlrover#797]
I apply the `examples/pytorch/nanogpt/ddp_elastic_job.yaml` in minikube. But it fails.

minikube config view：

- cpus: 18
- memory: 36g

master log：

<img src="https://youxing-typora.oss-cn-qingdao.aliyuncs.com/image-20231103212941615.png" alt="image-20231103212941615" style="zoom:67%;" />

worker-0 log：

<img src="https://youxing-typora.oss-cn-qingdao.aliyuncs.com/image-20231103200853127.png" alt="image-20231103200853127" style="zoom: 67%;" />

**Comment by workingloong** [comment]
Brain is not available in this example and we can ignore the error. Can you give me the complete log of worker-0？

**Comment by workingloong** [comment]
Brain is not available in this example and we can ignore the error. Can you give me the complete log of worker-0？

**Comment by youxingling** [comment]
Sorry, I mistakenly uploaded an incomplete image. Below is the complete log of worker-0.

<img src="https://youxing-typora.oss-cn-qingdao.aliyuncs.com/image-20231103200853127.png" alt="image-20231103200853127" style="zoom: 67%;" />

**Comment by workingloong** [comment]
I am very sorry! The image of nanogpt example has not been udpated in time after the codes are changed. I have re-build a new image `registry.cn-hangzhou.aliyuncs.com/intell-ai/dlrover:pytorch-example`. You can use the new image of the worker replica to submit a job like

```yaml
containers:
            - name: main
              # yamllint disable-line rule:line-length
              image: registry.cn-hangzhou.aliyuncs.com/intell-ai/dlrover:pytorch-example
              imagePullPolicy: Always
```
